services:
  backend:
    environment:
      - DB_NAME=korean-dict-db
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: krduffy/korean-dictionary:backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: krduffy/korean-dictionary:db
    environment:
      POSTGRES_DB: korean-dict-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    image: krduffy/korean-dictionary:frontend
    ports:
      - "5173:5173"
