# Generated by Django 5.0.1 on 2024-05-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='koreanword',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='koreanword',
            name='known_by',
            field=models.ManyToManyField(related_name='known_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='koreanword',
            name='studied_by',
            field=models.ManyToManyField(related_name='study_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sense',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_senses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sense',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='api.koreanword'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernote',
            name='word_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='api.koreanword'),
        ),
    ]
