# Generated by Django 5.0.1 on 2024-05-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreanword',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='koreanword',
            name='is_known',
        ),
        migrations.RemoveField(
            model_name='sense',
            name='created_by_user',
        ),
        migrations.AddField(
            model_name='koreanword',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sense',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_senses', to=settings.AUTH_USER_MODEL),
        ),
    ]
