# Generated by Django 5.0.1 on 2024-03-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hanjacharacter_words_that_contain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanjacharacter',
            name='words_that_contain',
        ),
    ]
