# Generated by Django 5.0.1 on 2024-05-14 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_koreanword_creator_alter_sense_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('note_text', models.CharField(max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='api.koreanword')),
            ],
        ),
    ]
