# Generated by Django 5.0.1 on 2024-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_hanjacharacter_is_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanjacharacter',
            name='decomposition',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='exam_level',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='explanation',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='grade_level',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='radical',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='strokes',
            field=models.SmallIntegerField(default=None),
        ),
    ]
