# Generated by Django 5.0.1 on 2024-04-01 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_hanjacharacter_words_that_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_is_studying', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='KnownWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_knows', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('note_text', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='api.user')),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
            ],
        ),
    ]
