# Generated by Django 5.0.1 on 2024-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_studyingword_knownword_usernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyingword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyingword',
            name='word_ref',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='word_ref',
        ),
        migrations.AddField(
            model_name='hanjacharacter',
            name='is_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='koreanword',
            name='is_known',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='KnownWord',
        ),
        migrations.DeleteModel(
            name='StudyingWord',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
    ]
