# Generated by Django 5.0.1 on 2024-04-09 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_studyingword_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
            ],
        ),
        migrations.CreateModel(
            name='StudyingWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('note_text', models.CharField(max_length=1000)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.koreanword')),
            ],
        ),
    ]
