# Generated by Django 5.0.1 on 2024-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_knownword_studyingword_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='koreanword',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
