# Generated by Django 5.0.1 on 2024-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dictionaryuser',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='dictionaryuser',
            name='username',
            field=models.CharField(unique=True),
        ),
    ]
