# Generated by Django 5.0.1 on 2024-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_koreanword_created_by_user_and_more'),
        ('dictionary_users', '0002_alter_dictionaryuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryuser',
            name='known_words',
            field=models.ManyToManyField(related_name='known_by', to='api.koreanword'),
        ),
        migrations.AddField(
            model_name='dictionaryuser',
            name='study_words',
            field=models.ManyToManyField(related_name='studied_by', to='api.koreanword'),
        ),
    ]
